### ISSUE TITLE
Test #1 - Photored a Busto Arsizio (VA), Corso Sempione / Via Torquato tasso

### ISSUE THREAD

**Issue by Max1234-Ita** [Luke1963/Segnalazioni-Velox-Italia#1]
Ciao, oggi passando per Busto Arsizio mi sono imbattuto in questo photored non ancora mappato.

Copre l'incrocio tra Corso Sempione e Via Tasso, in direzione Castellanza.

Ti allego uno screenshot di OsmAnd: ho messo un marcatore (arancione) in corrispondenza della fotocamera di rilevamento.

![image](https://github.com/Luke1963/Segnalazioni-Velox-Italia/assets/15315381/bb91777b-fafc-4ddf-aa31-597df269f3e7)

In ogni caso, se non ho visto male, ce n'è uno identico anche dall'altra parte dell'incrocio, che copre la direzione opposta.

Ciao e grazie!
Max

**Comment by Luke1963** [comment]
Ok, Mi attivo

Luke

**Comment by Luke1963** [comment]
Si tratta di Rilevatore Semaforico T-Red

**Comment by Luke1963** [comment]
Si tratta di un Rilevatore Semaforico T-Red

**Comment by Max1234-Ita** [comment]
Forse non è mappato del tutto...

**Comment by Luke1963** [comment]
Mappatura completata nella direzione ESE

![Screenshot 2024-04-18 alle 23 24 47](https://github.com/Luke1963/Segnalazioni-Velox-Italia/assets/167359083/d92e40f2-7d41-41a8-a2d7-57366021472e)
