### ISSUE TITLE
Rilevatore a Legnano, Via Milano / Via Gabinella

### ISSUE THREAD

**Issue by Max1234-Ita** [Luke1963/Segnalazioni-Velox-Italia#2]
Ciao, questo l'ho trovato a Legnano, Proveniendo da Via Milano in direzione SudEst

![image](https://github.com/Luke1963/Segnalazioni-Velox-Italia/assets/15315381/40510a36-c10c-4cb6-8ee4-5ac73781efe8)

Cartelli di rilevamento infrazioni non ne ho visti intorno, ma l'aspetto di dispositivo sanzionatorio ce l'ha.

**Comment by Luke1963** [comment]
mancano info di dettaglio
